name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5

      - name: Build Docker Image
        run: docker build -t task_management_system .

      - name: Deploy to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
          HOST: ${{ secrets.AWS_HOST }}
          USERNAME: ubuntu
        run: |
          echo "$SSH_PRIVATE_KEY" > private.pem
          chmod 600 private.pem
          ssh -i private.pem $USERNAME@$HOST "docker-compose -f /home/ubuntu/ProjectCloud/docker-compose.prod.yml up -d --build"

